scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['metrics-exporter:9100']
  - job_name: db-accessor
    scrape_interval: 5s
    static_configs:
    - targets: ['accessor:9091']