{
 "title": "Accessor Memstats Metrics And Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Pins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"db-accessor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"db-accessor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alloc Bytes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"db-accessor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Alloc Bytes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"db-accessor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=\"db-accessor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stack Sys Bytes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"db-accessor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Logs Volume",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (container_name) (count_over_time({job=\"containerlogs\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Accessor Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{container_name=\"db_accessor\"} |= ``"
    }
   ]
  },
  {
   "title": "Threads & Goroutines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "go_threads{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "go_goroutines{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Alloc & Sys Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstats Alloc Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Alloc Bytes Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes_total{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Other Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "go_memstats_other_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Next Gc Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstats Stack Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Stack Inuse Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstats Heap Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Heap Released Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Heap Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Heap Inuse Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Heap Idle Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Heap Alloc Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Other Memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstats Mspan Inuse Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Mallocs Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Lookups Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "go_memstats_lookups_total{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Frees Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "go_memstats_frees_total{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Gc Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Last Gc Time Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Buck Hash Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Mcache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstats Mcache Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Mcache Sys Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memstats Mcache Inuse Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Duration Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration Seconds Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "go_gc_duration_seconds_count{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration Seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration Seconds Sum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "go_gc_duration_seconds_sum{job=\"db-accessor\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}