{
 "title": "Accounts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"Accounts At Database\"  FROM accs_tb"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select COUNT(id) as \"Avaliable Phones\" from accs_tb where phone != 'None';\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"Scanned Groups\" FROM grps_tb "
    }
   ]
  },
  {
   "title": "Avaliable Phones Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select\n  tid \"Telegram ID\",\n  username as \"Username\",\n  concat('+', phone) as \"Phone Number\",\n  grps_tb.grp_name as \"Group Name\"\nfrom\n  (\n    SELECT\n      id as ruid,\n      tid,\n      username,\n      phone\n    FROM\n      accs_tb\n    WHERE\n      phone!='None'\n  ) as ru_accs\n  join ag_links_tb on ag_links_tb.id = ru_accs.ruid\n  join grps_tb on grps_tb.id = ag_links_tb.grp_id;"
    }
   ]
  },
  {
   "title": "RU Phone Numbers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select\n  tid \"Telegram ID\",\n  username as \"Username\",\n  concat('+', phone) as \"Phone Number\",\n  grps_tb.grp_name as \"Group Name\"\nfrom\n  (\n    SELECT\n      id as ruid,\n      tid,\n      username,\n      phone\n    FROM\n      accs_tb\n    WHERE\n      phone LIKE '7__________'\n  ) as ru_accs\n  join ag_links_tb on ag_links_tb.id = ru_accs.ruid\n  join grps_tb on grps_tb.id = ag_links_tb.grp_id;"
    }
   ]
  },
  {
   "title": "Scanned Groups",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT id as \"ID\", grp_name as \"Group Name\", grp_type as \"Type\" FROM grps_tb"
    }
   ]
  },
  {
   "title": "Group User Data",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 17 },
   "targets": [
    {
     "rawSql": "select ag_links_tb.id,\n       ag_links_tb.acc_id, \n       grps_tb.grp_name, \n       accs_tb.tid,\n       accs_tb.username,\n       accs_tb.phone\n\nfrom ag_links_tb \n    join grps_tb on ag_links_tb.grp_id=grps_tb.id \n    join accs_tb on ag_links_tb.acc_id=accs_tb.id;\n"
    }
   ]
  }
 ]
}